#!/Users/danielmelchor/Documents/CodeProjects/search-engine/backend/venv/bin/python3

import sys
from main import start_server
from utils import parse_args

if __name__ == '__main__':
    host, port = parse_args()
    start_server(host, port)
